name: Pre-Review Full Rule Enforcement

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
      - develop

jobs:
  full-review:
    name: Code Review and Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygit2 gitpython

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install Node Dependencies
        run: |
          npm ci || npm install --legacy-peer-deps

      - name: Run ESLint
        id: lint
        continue-on-error: true
        run: |
          npm run lint -- --format json > lint-output.json 2>/dev/null || true
          echo "LINT_STATUS=$?" >> $GITHUB_ENV

      - name: Run Security Audit
        id: audit
        continue-on-error: true
        run: |
          npm audit --json > audit-output.json 2>/dev/null || true
          echo "AUDIT_STATUS=$?" >> $GITHUB_ENV

      - name: Check for Dangerous Deletions
        id: deletion-check
        run: |
          DELETED_FILES=$(git diff --name-status origin/${{ github.base_ref }}...HEAD | grep ^D || true)
          if [ ! -z "$DELETED_FILES" ]; then
            echo "::warning::The following files are being deleted:"
            echo "$DELETED_FILES"
            echo "DELETIONS_FOUND=true" >> $GITHUB_ENV
          else
            echo "✅ No deletions detected"
            echo "DELETIONS_FOUND=false" >> $GITHUB_ENV
          fi

      - name: Run Semantic Diff Analysis
        id: diff-analysis
        run: |
          # Get the diff and pipe it to the Python script
          git diff origin/${{ github.base_ref }}...HEAD | python scripts/analyze_diff.py

          # Set the risk level based on the analysis
          if grep -q "risk-high" diff.html; then
            echo "RISK_LEVEL=High" >> $GITHUB_ENV
          elif grep -q "risk-medium" diff.html; then
            echo "RISK_LEVEL=Medium" >> $GITHUB_ENV
          else
            echo "RISK_LEVEL=Low" >> $GITHUB_ENV
          fi

      - name: Upload Analysis Report
        uses: actions/upload-artifact@v4
        with:
          name: code-analysis-report
          path: |
            diff.html
            lint-output.json
            audit-output.json
          retention-days: 7

      - name: Comment PR with Analysis Results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('diff.html', 'utf8');
            
            const summary = `## Code Analysis Summary
            
            - Risk Level: ${{ env.RISK_LEVEL }}
            - Linting Status: ${process.env.LINT_STATUS === '0' ? '✅ Pass' : '⚠️ Issues Found'}
            - Security Audit: ${process.env.AUDIT_STATUS === '0' ? '✅ Pass' : '⚠️ Issues Found'}
            - File Deletions: ${process.env.DELETIONS_FOUND === 'true' ? '⚠️ Yes' : '✅ No'}

            [View Full Report](${context.payload.repository.html_url}/actions/runs/${context.runId}/artifacts)`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

      - name: Check Results
        if: always()
        run: |
          if [ "${{ env.LINT_STATUS }}" != "0" ] && [ ! -z "${{ env.LINT_STATUS }}" ]; then
            echo "::warning::Linting issues found. Please review the logs."
          fi
          if [ "${{ env.AUDIT_STATUS }}" != "0" ] && [ ! -z "${{ env.AUDIT_STATUS }}" ]; then
            echo "::warning::Security vulnerabilities detected. Please review the audit report."
          fi
          if [ "${{ env.DELETIONS_FOUND }}" == "true" ] || [ "${{ env.RISK_LEVEL }}" == "High" ]; then
            echo "::error::Action required: File deletions or High risk detected. Manual review required."
            exit 1
          fi
